#!/bin/bash

# Load all the basch scripts
if [ -f "/etc/solt/solt.conf" ]; then
    source /etc/solt/solt.conf
fi

# Update common folder
function _update_solus_source_common {
    pushd $phabsource_dir/common
        git pull
    popd
}

# Update solussource Folder
function _update_solus_source {
    _user_check
    pushd $phabsource_dir
        make clone -j20
        _show_info "Repo updated"
        make pull -j20
        _show_info "Packages updated"
    popd
}

# Search inside SolusSource folder
function _search_solus_source {
    pushd $phabsource_dir
        ag --silent -QH $term ./*/$place
    popd
}

function _search_solus_source2 {
    pushd $phabsource_dir
       ag --silent -Ql $term ./*/$place
    popd
}
function _remove_solus_source_pkg {
    pushd $phabsource_dir
        go run common/Go/deprecate_packages.go
    popd
}
    
