#!/bin/bash

# Load all the basch scripts

for file in /usr/share/solt/*; do
    source /usr/share/solt/solt_log
done

if [ -f "/etc/solt/solt.conf" ]; then
        source /etc/solt/solt.conf
fi

# Checks if the folder already exists
function _file_check {
    if [ -z "$reponame" ]; then
        _show_error "Please input package file name."
        exit 5
    elif [ -d "$@" ]; then
        _show_error "Directory already exists."
        exit 17
    fi
}

# Checks if you have root privileges
function _root_check {
    if [[ "$(id -u)" != "0" ]]; then
        _show_error "This operation requires admin privileges"
        exit 87
    fi
}

# Checks if you have root privileges
function _user_check {
    if [[ "$(id -u)" = "0" ]]; then
        _show_error "This operation should be run as user"
        exit 87
    fi
}

# Check which shell its using and executes it

function _exec_shell {
    if [[ $(echo $0) = "bash" || "/bin/bash" ]] ; then
        exec bash
    elif [[ $(echo $0) = "zsh" || "/bin/zsh" ]]; then
        exec zsh
    fi
}
