#!/bin/bash

# Load all the basch scripts
for file in /usr/share/solt/*; do
    source ~/.config/solt/solt.conf
    source /usr/share/solt/solt_common
    source /usr/share/solt/solt_log
    source /usr/share/solt/solt_functions
done

# Create a repo package
function _create_repo {
    _file_check $build_dir/$reponame
    mkdir -p $build_dir/$reponame 
    cd $build_dir/$reponame
        _show_request "Please enter package source url"
        read URL
            $common_dir/$yauto_path ${URL}
        git init;
        _create_makefile
        _show_confirm "Makefile created"
    exec bash
}

# Update a repo
function _update_repo {
    _file_check $build_dir/$reponame
    git clone ssh://vcs@dev.getsol.us:2222/source/$reponame.git $build_dir/$reponame
    cd $build_dir/$reponame
        _show_request "Please enter new version no and url"
        read VERSION URL
            python $yupdate_path ${VERSION} ${URL}
    exec bash
}

# Clone a repo
function _clone_repo {
    _file_check $build_dir/$reponame
    git clone ssh://vcs@dev.getsol.us:2222/source/$reponame.git $build_dir/$reponame
    cd $build_dir/$reponame
    exec bash
}

# Clone and bump a repo
function _bump_repo {
    _file_check $build_dir/$reponame
    git clone ssh://vcs@dev.getsol.us:2222/source/$reponame.git $build_dir/$reponame
    cd $build_dir/$reponame
        make bump
    exec bash
}

# Clone a Diff for a repo
function _diff_repo {
    _clonefolder_check
    git clone ssh://vcs@dev.getsol.us:2222/source/$reponame.git $clone_dir/$reponame
    cd $clone_dir/$reponame
        arc patch $diff
    exec bash
}

# Clone an initial diff
function _initial_repo {
    _file_check $build_dir/$reponame
    mkdir -p $build_dir/$reponame
    cd $build_dir/$reponame
        git init
        git commit -s -m "Test repo" --allow-empty
        arc patch $diff
    exec bash
}
