#!/bin/bash

for file in /usr/share/solt/*; do
    source /usr/share/solt/solt_log
done

function _solt_check {
    if [ -f "$HOME/.config/solt/solt.conf" ]; then
        :
    else
        _show_info "Please set up a solt.conf"
        read -p "Would you like to copy a default config to ~/.config/solt? [y/n]" choice
        case $choice in
            y)
            mkdir -p ~/.config/solt ;
            cp -vR /usr/share/solt/solt_default.conf ~/.config/solt/solt.conf
            _show_info "Please edit your config file accordently to your liking"
            ;;
            
            n) exit 0 
            ;;
        esac
    fi

    if [ -f "$HOME/.config/solt/solt.conf" ]; then
        source $HOME/.config/solt/solt.conf
    else
        source /usr/share/solt/solt_default.conf
    fi
}
