#!/bin/bash

# Prints out a red color bar
function _show_error {
    printf "\e[1;37;41m $@ \e[0m\e[31m\e[0m\n"
}

# Prints out a green color bar
function _show_confirm {
    printf "\e[1;37;42m $@ \e[0m\e[32m\e[0m\n"
}

# Prints out a orange color bar
function _show_info {
    printf "\e[1;37;43m $@ \e[0m\e[33m\e[0m\n"
}

# Prints out a vilote color bar
function _show_request {
    printf "\e[1;37;45m $@ \e[0m\e[35m\e[0m\n"
}

function _bold {
    printf "\033[1m $@ \033[0m\n"
}
