#!/bin/bash

# Load all the basch scripts
for file in /usr/share/solt/*; do
    source /usr/share/solt/solt_log
    source /usr/share/solt/solt_functions
done

if [ -f "/etc/solt/solt.conf" ]; then
        source /etc/solt/solt.conf
fi

# Symlinks to common folder inside the Packaging folder
function _create_common {
    ln -sv $build_dir/common .
    ln -sv common/Makefile.common .
    ln -sv common/Makefile.toplevel Makefile
    ln -sv common/Makefile.iso .
}

# Creates a Makefile  
function _create_makefile {
    echo "include ../Makefile.common" > Makefile;
}

# Checks if a common folder exists
function _clonefolder_check {
    if [ ! -d "${clone_dir}" ]; then
        _show_info "${clone_folder} folder did not exist creating it"
        mkdir -p $build_dir/${clone_folder}
        pushd $build_dir/${clone_folder}
            _create_common
        popd
    fi
}

# Look up the base pkg for a pkgconfig() builddep
function _search_pkgconfig {
        python $common_dir/$pkgconfig_path $pkg
}
