#!/bin/bash

# Load all the basch scripts
for file in /usr/share/solt/*; do
    source /usr/share/solt/solt_log
done

# Check if config file in user Home is there
function _solt_check {
    if [ -f "$HOME/.config/solt/solt.conf" ]; then
        :
    else
        _show_error "Please set up a solt.conf"
        echo ""
        read -p "Would you like to copy a default config to ~/.config/solt? [y/n]" choice
        echo ""
        case $choice in
            y)
            mkdir -p ~/.config/solt ;
            echo "Copy solt default config to ~/.config/solt"
            cp -R /usr/share/solt/solt_default.conf ~/.config/solt/solt.conf
            echo ""
            _show_request "Please edit your config file accordently to your liking inside ~/.config/solt/solt.conf"
            echo ""
            ;;
            
            n) exit 0 
            ;;
        esac
    fi
}
